//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDownloader.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HowItWorks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HowItWorks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicDownloader.Resources.Pages.HowItWorks", typeof(HowItWorks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the download button..
        /// </summary>
        public static string ClickDownloadButton {
            get {
                return ResourceManager.GetString("ClickDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each song should be on a separate line..
        /// </summary>
        public static string EachSongOnSeparateLine {
            get {
                return ResourceManager.GetString("EachSongOnSeparateLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search process has started, it may take several minutes, depending on the number of songs..
        /// </summary>
        public static string SearchHasStarted {
            get {
                return ResourceManager.GetString("SearchHasStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use the free music downloader?.
        /// </summary>
        public static string UserGuideTitle {
            get {
                return ResourceManager.GetString("UserGuideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the search is completed, the .zip archive with files and a text document that lists not found the songs will automatically be downloaded..
        /// </summary>
        public static string WhenSearchIsCompleted {
            get {
                return ResourceManager.GetString("WhenSearchIsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the input field we write the name of the artist and the song..
        /// </summary>
        public static string WriteSongsIntoInput {
            get {
                return ResourceManager.GetString("WriteSongsIntoInput", resourceCulture);
            }
        }
    }
}
